services:
  - type: web
    name: cyber-caliph-elite
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gthread -w 1 --threads 8 --preload --timeout 120 app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: AFFILIATE_LINK
        value: https://kie.ai?ref=0e3195dd062bf11f0da7496dd3c1bf6
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: CYBER_MASTER_KEY
        value: c2VjcmV0X2tleV8zMl9ieXRlc19sb25nX2Vub3VnaA==
      - key: YOUTUBE_CLIENT_ID
        sync: false
      - key: YOUTUBE_CLIENT_SECRET
        sync: false
      - key: YOUTUBE_REFRESH_TOKEN
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: CHANNEL_ID
        value: "@CursedMedicineEG"
      - key: CHANNEL_URL
        value: "https://www.youtube.com/@CursedMedicineEG"
